### ISSUE TITLE
Capture metrics for external volume resizing

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-resizer#37]

**Comment by bertinatto** [comment]
What metrics should the external-resizer emit?

If I read correctly, in-tree CSI resizing already emits metrics for duration, errors, statuses etc.

I suppose the duration there isn't exactly accurate (because the resizing is performed externally), is that correct? If so, would recording the duration of the operation enough here?

**Comment by msau42** [comment]
@yuxiangqian is planning to add a metrics library to csi-lib-utils that all the sidecars can use

**Comment by msau42** [comment]
The main benefit of sidecar metrics is to get per operation latency and error metrics which cannot be done in the intree controller for CSI plugins

**Comment by gnufied** [comment]
@bertinatto we do not emit resizing metrics for CSI drivers from in-tree code.  Where did you see the metric being emitted? The in-tree controller simply hands over the control to the external controller.

@msau42 Will the library capture just operation metrics or total latecy metrics?

**Comment by yuxiangqian** [comment]
@gnufied @msau42 I have not got a chance to work on the lib yet. I will come back to that after the snapshot to beta project is done. But the plan is to have it in [csi-lib-utils](https://github.com/kubernetes-csi/csi-lib-utils). My very initial thought is to have common utilities, like metric registration with prometheus, timestamp cache struct etc. defined for sharing. The real reporting would still happen likely in sidecar controllers. Might worth a KEP?
