### ISSUE TITLE
Ensure resizer handles double processing of PVCs without problems.

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-resizer#4]
xref - https://github.com/kubernetes/kubernetes/pull/71611

**Comment by mlmhl** [comment]
It seems that the race condition mentioned in https://github.com/kubernetes/kubernetes/issues/71470#issuecomment-442248513 does not exist in external-resizer. The in-tree expand controller uses a custom [sync mechanism](https://github.com/kubernetes/kubernetes/blob/10bb353a95c53831b9131e8c4cc539c87f34a0d6/pkg/controller/volume/expand/pvc_populator.go#L84) to resync pvcs, which is the root of the problem. But in external-resizer, we uses `SharedInformer`'s [resync mechanism](https://github.com/kubernetes-csi/external-resizer/blob/7373866c8a4850da71cab7ecb7e803beee1dd1ff/pkg/controller/controller.go#L97). With this mechanism,  `SharedInformer` will send us `Update` events periodically, the old object and new object are the same in these events. So this [judgement](https://github.com/kubernetes-csi/external-resizer/blob/7373866c8a4850da71cab7ecb7e803beee1dd1ff/pkg/controller/controller.go#L132) inside the update handler will intercept these events.

But when I review the code, I found that this mechanism raises another race condition, consider the following example:

1. User requests size 1Gi -> 2Gi
2. Resizer resizes the volume and adds a `PersistentVolumeClaimFileSystemResizePending` condition
3. Kubelet starts to resize file system
4. User requests size 2Gi -> 3Gi
5. Resizer resizes the volume and updates the `PersistentVolumeClaimFileSystemResizePending` condition.
6. Kubelet finishes the first resize request and clear the conditions.
7. Kubelet performs the second resize request.

Although second resize request can be finished in step 7, but the PVC condition is not right during step 6 and step 7(wanted `PersistentVolumeClaimFileSystemResizePending`, got empty), because we won't process the PVC again(due to the judgement mentioned above).

To resolve this problem, I think we need to remove the judgement mentioned above and add a version check mechanism like https://github.com/kubernetes/kubernetes/pull/71611. @gnufied Do you have any other good ideas?

**Comment by gnufied** [comment]
Yeah I agree, I think we do need a resourceVersion check added in https://github.com/kubernetes/kubernetes/pull/71611 to external resizer as well.

**Comment by mlmhl** [comment]
@gnufied As the PR #6 is already merged, could we close this issue?
